version: '3.4'

services: 
    application:
        build:
            dockerfile: build/Dockerfile
            context: ../
        ports:
            - 127.0.0.1:8081:8081
        environment:
            DB_DSN: mongodb://root:root@localhost:27017
    db:
        image: mongo:4.4.5
        ports:
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root