version: '3.4'

services: 
    application:
        container_name: application
        build:
            dockerfile: build/Dockerfile
            context: "."
        ports:
            - 8091:8091
        depends_on:
            - postgres
        environment:
            PORT: 8091
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USER: admin
            DB_PASSWORD: admin
            DB_DATABASE: todo
            MIGRATIONS_PATH: file:///migrations
        networks:
            - todo
        command: ["/wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "/app"]

    postgres:
        container_name: postgres
        image: postgres:13.2
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: todo
        networks:
            - todo

    grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        networks:
            - todo

    prometheus:
        image: prom/prometheus:latest
        ports:
            - 9090:9090
        volumes:
            - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - todo

networks:
    todo: